### ISSUE TITLE
"vendor" libs must be specified as symbols in include_js, while standalone files must be strings

### ISSUE THREAD

**Issue by weyus** [mintdigital/asset_hat#10]
There needs to be some standard symbolizing or stringifying in AssetHat.  If you want to pull jquery or prototype from the Google CDN, you must use symbols (:jquery, :prototype) to specify them.  In addition, it appears that you must use strings for non-vendor JS that you are pulling in.

Not sure if this applies to bundle names or not.  But it's confusing that there are two different ways that you have to specify libraries in the include_js call.

**Comment by rondevera** [comment]
As noted, there are a few different ways to include custom files and known vendors:
- `include_js :known_vendor` (using a symbol because the vendor identity is what matters)
- `include_js 'my-file'` (using a string because the exact characters are what matter)
- `include_js :bundle => 'my-bundle'` _or_ `include_js :bundle => :my_bundle` (The symbol case makes more sense, but the string variant is supported, too.)

Calling `include_js` with a symbol means that you want to use the built-in vendor lookup; calling it with a string means that you're looking up your own file. This is by design, and targets two use cases:
- The simplest possible inclusion of common JS libraries, e.g., `include_js :jquery`.
- Easy transition from Rails' default helpers, e.g., `javascript_include_tag 'my-file'` -> `include_js 'my-file'`.

**Comment by weyus** [comment]
Thanks - that makes sense now.  Is this is the docs somewhere?  I never saw it.  I would suggest that it be slightly more prominent (in the README, perhaps?).

Thanks again.
